### ISSUE TITLE
origin/main does not compile: semantic merge conflict between #608 and #609 (generator CapturedVariables)

### ISSUE THREAD

**Issue by nickna** [nickna/SharpTS#610]
## Summary

`origin/main` at `2a5046de` **does not compile**. `Compilation/ILCompiler.Generators.cs` references `analysis.CapturedVariables`, but that field was removed from `GeneratorStateAnalyzer.GeneratorFunctionAnalysis` by #609.

```
Compilation/ILCompiler.Generators.cs(70,..): error CS1061: 'GeneratorStateAnalyzer.GeneratorFunctionAnalysis' does not contain a definition for 'CapturedVariables'
Compilation/ILCompiler.Generators.cs(71,..): error CS1061: ...
Compilation/ILCompiler.Generators.cs(73,..): error CS0117: ...
```

## Root cause — semantic merge conflict

This is a classic semantic (logical) merge conflict; neither PR's diff textually conflicted, so GitHub merged both cleanly, but the result is uncompilable:

- **#608** (`019b320b`, nested-function lifter) **added** `ExcludeTopLevelFunctionsFromCaptures`, which reads `analysis.CapturedVariables`, plus the supporting `CollectTopLevelFunctionNames` / `_topLevelFunctionNamesByModule` machinery. Its purpose: stop a generator state machine from defining never-populated *fields* for top-level function names that appeared in the captured set.
- **#609** (`3ba5789b`, #541) **removed** `CapturedVariables` from `GeneratorFunctionAnalysis` and stopped hoisting captured outer-scope variables into state-machine fields entirely — generators now read them **live** in `MoveNext` (mirroring the async-generator path).

`merge-base(#608, #609) == 019b320b` and #609's branch (`3ba5789b`) was created **before** #608 merged, so it never saw `ExcludeTopLevelFunctionsFromCaptures`. The textual merge kept #608's helper while #609 deleted the field it depends on. CI passed on each PR branch (each tested against a main that did *not* contain the other change); the merge commit itself was never built.

## Correct resolution

Since #609 no longer materialises captured-variable fields, #608's `ExcludeTopLevelFunctionsFromCaptures` (and its now-unread `CollectTopLevelFunctionNames` / `_topLevelFunctionNamesByModule` chain) is **dead** — removing it restores the build and changes no runtime behavior (the helper can no longer compile or run). #608's actual fix (`NestedFunctionLifter.Lift`) is untouched. The #608 "top-level function referenced as a value inside a generator" scenario (`const h = helper; yield h()`) still works because #609's live-read path resolves it through the normal function-value path in both interpreted and compiled mode.

Fix PR incoming.
