### ISSUE TITLE
compiled: lodash init fails after #276 — getNative path throws 'object is not a function'

### ISSUE THREAD

**Issue by nickna** [nickna/SharpTS#302]
## Summary

With #276 fixed (value-form `Math.max`/`JSON.stringify` wrappers now populated), compiled-mode lodash initialization gets one step further but still fails. `RealPackageSmokeTests.Lodash_Compiled` — which only asserts that lodash *loads* (`typeof _ === "function"`) — now throws during module init:

```
System.Exception: TypeError: object is not a function
    at $Runtime.InvokeMethodValue(Object, Object, Object[])
    at InvokeStub_<>c__InnerFuncDC378_getNative.Invoke(...)
    ...
    at $Module_lodash.$Initialize()
    at $Module_lodash.$GetExports()
```

The failure is inside lodash's `getNative(object, key)` helper (`baseIsNative` / `getValue`), invoking something that resolves to a non-callable object in compiled mode — a value-form dispatch gap distinct from #276's Math/JSON singletons.

## Repro

```js
const _ = require('lodash');
console.log(typeof _);     // interp: "function"; compiled: TypeError: object is not a function
```

`Lodash_Interpreter` passes; only the compiled path fails.

## Status

`Lodash_Compiled` remains `[SkippableFact(Skip=...)]`, now pointing at this issue instead of #276. Unskip when the getNative value-form dispatch is resolved. (`_.chunk`/`_.flatten` returning wrong values in compiled mode — noted in the test — is a further, separate behavioral gap.)

## Environment
- Branch builds on `origin/main` @ 0f409b43 + the #276/#281/#296/#297/#300 batch; .NET 10.0, Windows 11

**Comment by nickna** [comment]
Closing in favor of #307. Triage during PR #308 disproved this issue's hypothesis (a value-form dispatch gap in lodash's `getNative`). The real root cause is a compiler closure bug — inner function *declarations* nested inside an arrow / function expression capture enclosing locals by value-snapshot at hoist time instead of by live reference, so `getValue` / `Object` / `symToStringTag` read back `null` (`typeof null === "object"` → "object is not a function"). #307 has the minimal repro and a concrete fix plan (a live `$arrowScopeDC` reference for inner functions, mirroring `$functionDC`). `Lodash_Compiled` stays skipped, pointing at #307.
