### PR TITLE
Fix un-buildable main: ParameterInfo[]/Type[] mismatch in generator instance stubs (re-enables #723/#737/#738/#739)

### LINKED ISSUE #720: Compiled mode: async/generator private methods (`async #m`, `*#m`) emit invalid IL / unsupported
## Summary

In **compiled mode**, an **async** or **generator** ES2022 private method is not emitted through a state machine — `EmitPrivateMethodBody` (`Compilation/ILCompiler.Classes.Methods.cs`) emits the body linearly into the `__private_<name>` method regardless of `IsAsync`/`IsGenerator`. The interpreter handles both correctly.

Discovered while completing #696 (private-method optional params). Independent of #696 — reproduces with **required** params that parsed before #696.

## Repro — async private method

```ts
class Q {
  async #p(x: number): Promise<number> { return x; }
  go(): Promise<number> { return this.#p(5); }
}
new Q().go().then(v => console.log(v));
```

`--compile … --verify`:
```
[IL Error] Q.__private_p: StackUnexpected {Offset=1, Found=ref 'object', Expected=ref 'Task`1<object>'}
```
The method is declared to return `Task<object>` (see `ILCompiler.Classes.cs` private-method definition: `returnType = method.IsAsync ? _types.TaskOfObject : typeof(object)`) but the linear body `return x` leaves a bare `object` on the stack. It happens to run (JIT lenient + compiled `await` of a non-task returns the value), but the IL is invalid.

## Repro — generator private method

```ts
class G {
  *#p(x: number): Generator<number> { yield x; yield x + 1; }
  go(): number { let s = 0; for (const v of this.#p(5)) s += v; return s; }
}
console.log(new G().go());
```
`--compile`:
```
Compile Error: Yield not supported in this context
```

## Expected

Async/generator private methods compile through the same state-machine path as their public counterparts (`AsyncStateMachineBuilder` / generator lowering), so `__private_p` returns a real `Task<object>` / `IEnumerable<object>` and `yield` is supported.

## Fix sketch

`EmitPrivateMethodBody` needs to branch on `method.IsAsync`/`method.IsGenerator` and drive the corresponding state-machine builder instead of emitting the body inline, mirroring how public class methods are emitted. Parameter defaults (the prologue added in #696) should then move into the state-machine entry prologue (as `AsyncMoveNextEmitter` already does for public methods).

### LINKED ISSUE #723: Compiled: class methods (instance + static) ignore default parameter values
## Summary

In **compiled** mode, **class methods** — both instance and static — ignore default parameter values entirely. A missing argument is left at its CLR zero value (`0` for `number`, `null` for reference types) instead of the parameter's default. The **interpreter** handles all of these correctly. Top-level **function declarations** and **arrow / function expressions** apply defaults correctly in compiled mode (see #646); only class methods are affected.

## Repro

```ts
class C {
  m(a: number, b: number = 2) { return a + b; }
  s2(a: string, b: string = "z") { return a + b; }
  static st(a: number, b: number = 2) { return a + b; }
}
console.log(new C().m(5));     // interpreted: 7    compiled: 5      (b dropped → 0)
console.log(new C().s2("x"));  // interpreted: xz   compiled: xnull  (b dropped → null)
console.log(C.st(5));          // interpreted: 7    compiled: 5
```

When every argument is supplied the methods behave correctly (e.g. `new C().m(5, 10)` ⇒ `15` in both modes); only the omitted-argument (default) path is broken.

## Root cause

`EmitMethod` (`Compilation/ILCompiler.Classes.Methods.cs`) defines the method's parameters but never applies defaults: unlike the arrow path it calls neither `ParameterTypeResolver.WidenDefaultedParamsToObject` nor `ILEmitter.EmitDefaultParameters`, and unlike the top-level-function path it generates no `OverloadGenerator` lower-arity overloads. So a call supplying fewer arguments than parameters pads the missing slots with the CLR default and the body observes `0`/`null`.

## Why this is filed separately from #698

#698 (a default that references an earlier parameter) is now fixed for arrows / function-expressions / function-declarations in both modes, and for methods in the **interpreter**. The compiled-method earlier-param case (`m(a, b = a * 2)` ⇒ `5` instead of `15`) is a strict subset of *this* broader gap — compiled methods drop **all** defaults, not just earlier-param ones — so it cannot be closed without fixing this first.

Fixing it needs care around **virtual dispatch / override-signature matching**. The arrow-style fix (widen defaulted params to `object`) changes a method's CLR signature and would break override / interface-implementation matching against a base or subclass whose same-named method has no defaults (e.g. `class Base { m(a, b = 2) {} }` vs `class Derived extends Base { m(a, b) {} }` — both must stay signature-compatible). The safer route is likely method-level arity overloads analogous to `OverloadGenerator` for free functions, with method dispatch selecting the right arity.

(Class *expression* methods in `Compilation/ILCompiler.Classes.ClassExpressions.cs` DO call `EmitDefaultParameters` and so may behave differently — not verified here. Note that path applies defaults via the null/`$Undefined` check, which cannot observe a value-type `double`/`bool` slot, cf. #705.)

## Discovered

While implementing #698. Interpreter parity confirmed correct for all the above.

### PR DESCRIPTION
**Pull request by nickna**
## What this fixes

`origin/main` currently **does not compile**:

```
Compilation/ILCompiler.AsyncGenerators.cs(376,107): error CS1503: Argument 6: cannot convert from 'System.Reflection.ParameterInfo[]' to 'System.Type[]?'
Compilation/ILCompiler.Generators.cs(557,107): error CS1503: Argument 6: cannot convert from 'System.Reflection.ParameterInfo[]' to 'System.Type[]?'
```

This is a **semantic merge conflict** between two independently-correct PRs that were merged without being rebased onto each other:

- **#769** (`e64f3adb`, compiled closures #724/#725) added `EmitGeneratorFunctionDCInit(…, Type[]? paramTypes)` and called it from the generator / async-generator **instance** stub methods, passing their `paramTypes` local (then a `Type[]`).
- **#786** (`b95b6945`, "Fix #720: async/generator private methods emit invalid IL") changed that same `paramTypes` local from the AST-resolved `Type[]` to `methodBuilder.GetParameters()` (a `ParameterInfo[]`) — deliberately, so boxing is decided from the method's **actual IL signature** (a private method's params are all `object` slots; boxing an AST-resolved `double` into an `object` slot is a `StackUnexpected`).

Each compiled in isolation; together a `ParameterInfo[]` flows into a `Type[]?` parameter → CS1503. (Neither side is #787 — that is simply what surfaced this when I went to verify it.)

## The fix

Convert at the two call sites with `.Select(p => p.ParameterType).ToArray()` — the dominant idiom in this codebase for `GetParameters()` → `Type[]` (`ILCompiler.Classes.Methods.cs:1250`, `Static.cs:438`, `Constructors.cs:363`). This preserves #720's "box from the actual IL signature" intent: for a private/all-object or #737-widened-to-`object` slot, `ParameterType` is `object`, so `IsValueType` is false and nothing is spuriously boxed — exactly matching the field-seeding loop directly above each call.

```diff
-            EmitGeneratorFunctionDCInit(il, smBuilder.FunctionDCField, method, funcDCKey, paramOffset: 1, paramTypes);
+            EmitGeneratorFunctionDCInit(il, smBuilder.FunctionDCField, method, funcDCKey, paramOffset: 1,
+                paramTypes.Select(p => p.ParameterType).ToArray());
```

(I considered widening the helper to `ParameterInfo[]?` instead, but it genuinely operates on `Type` — it boxes with the element and checks `.IsValueType` — and two of its four callers pass `null`; the call-site conversion is the smaller, more idiomatic change.)

## Why this matters / relation to #723 #737 #738 #739

The compiled default/optional-parameter cluster (#705/#723/#737/#738/#739) was implemented and merged in #787, but the later merge above left `main` un-buildable, so those features could not actually run. With the build repaired I verified all four issues' repros, compiled output matching the interpreter:

- **#723** instance/static method defaults — `new C().m(5)`→`7`, `C.st(5)`→`7`, string default→`xz` ✓
- **#737** value-type defaults on instance/static + generator methods, incl. the same-arity override-safety case ✓
- **#738** `--compile --ref-asm` value-call no longer shifts args (`f(4)`→`7`) ✓
- **#739** omitted optional reads `undefined` (`typeof`→`"undefined"`) ✓

Existing coverage `Generator_InstanceMethodCallbackMutatesCapturedParameter` — an instance generator method whose arrow mutates a captured **value-type** parameter, the exact path repaired here — exercises the boxing branch and passes. Full unit suite green (13352 passed, 0 failed, 1 skipped).

## Follow-ups filed (pre-existing gaps surfaced while verifying)

- **#790** — a base-typed call to a derived override that *adds* trailing optional params dispatches to the base method (a different-arity override is not a CLR vtable override). Affects value- and reference-type defaults and no-default optionals; distinct from the same-arity override group #787 handles.
- **#792** — a defaulted generator/async-generator parameter that is *also* captured by a nested arrow ignores its default on omitted args (the default prologue writes the state-machine field, but a captured param's live storage is the function-DC field). Intersection of #737 and #724/#725; reproduces for free-function generators too, so independent of this build fix.

No new tests added: the break is compile-time (caught by any build) and its runtime path is already covered; the two follow-ups are failing cases tracked as issues.

Fixes #723, #737, #738, #739.

### CODE REVIEW

**Comment by nickna** [comment]
Closing as **superseded** — a concurrent session fixed the same build break first.

This PR repaired an un-buildable `main` (CS1503 ×2: `ParameterInfo[]` → `Type[]?` in the generator/async-generator instance stubs, from the #769×#786 merge seam) by converting at the two call sites. While it was open, `main` advanced to `e8f39905`, where commit `35640416` ("Fix broken build: EmitGeneratorFunctionDCInit param type (ParameterInfo[])") already fixed the identical break via the equivalent **opposite** approach — widening the helper's parameter to `ParameterInfo[]?` so the stub's `methodBuilder.GetParameters()` flows in directly. Both are correct and box from the actual IL signature; theirs landed first.

CI here is red only because the PR is built **merged with the now-fixed main**, which produces the reverse mismatch (`Type[]` → `ParameterInfo[]?`). There is no longer any code change to make.

Verification still stands and was re-run against current `main` (`e8f39905`):

- **#723 / #737 / #738 (`--ref-asm`) / #739** — all confirmed working, compiled output matching the interpreter.
- Filed **#790** (a base-typed call to a derived override that *adds* trailing optional params dispatches to the base method) and **#792** (a defaulted generator/async-generator parameter that is *also* captured by a nested arrow ignores its default on omitted args) as pre-existing gaps surfaced while verifying — both still reproduce on `e8f39905`.
