### ISSUE TITLE
Number predicate method-value program is rejected despite valid direct calls

### ISSUE THREAD

**Issue by nickna** [nickna/SharpTS#1801]
Found while verifying #1599's metadata-ownership migration. This report owns the separate semantic correction below; it closes no ownership, construction, registry or shared-infrastructure audit work.

All sources were compiled independently with TypeScript 5.9.3 (ES2022/CommonJS, noEmitOnError, skipLibCheck) and run with Node v22.23.2 before the corresponding SharpTS probes. Original sources, outputs, diagnostics and thirty-second execution deadlines remain retained. Compile with `--no-tsconfig --compile main.ts -o main.dll --standalone --verify`; execute only IL-verified outputs.

Probe `number_alias`, SHA-256 `4009d98fe33d6d46a5fa669eaac87f7d128e7b8053964b66ba540296c31e7a7f`:

```ts
const N:any=Number;console.log(N.isNaN(NaN),N.isFinite(3),N.isInteger(3),N.isSafeInteger(3),N.isInteger(3.5));console.log(N.isNaN===Number.isNaN,N.isFinite.name,N.isFinite.length);
```

Original TypeScript/Node stdout:

```text
true true true true false
true isFinite 1
```

Both baseline and integrated SharpTS reject this TypeScript-accepted source before saving an assembly:

```text
Property 'isNaN' does not exist on type 'NumberConstructor'. Did you mean 'NaN'?
```

No IL verification or execution is claimed for the rejected program. The control containing the same predicate calls without its method-identity/name/length expressions passes on both compilers:

Probe `number_call_control`, SHA-256 `a9cb3fd308b33876b3717b268ecfe17e80a5a6d37d08fcb98ceef7d94d8bf971`:

```ts
const N:any=Number;console.log(N.isNaN(NaN),N.isFinite(3),N.isInteger(3),N.isSafeInteger(3),N.isInteger(3.5));
```

Original TypeScript/Node stdout:

```text
true true true true false
```

Required correction:

- Accept the exact original program and reproduce both original output lines from an IL-verified standalone output within thirty seconds.
- Investigate static Number member typing in call and value positions, aliases and direct constructor references; determine the rejecting expression rather than inferring it solely from the diagnostic.
- Retain the passing predicate-call control and add focused method-value, identity, name/length and invalid-member regressions. Preserve the original source and diagnostic.

Provenance:

- Unchanged baseline: #1800, merged `36762c66cd66ca15d618f8ad4d6050b3867578b4`, compiler SHA-256 `57b90716b1d83dbe6a5f276791f3e9ad026cd93d9c790b0d52c403cfc631f084`.
- Static-dispatch integration: `36762c66cd66ca15d618f8ad4d6050b3867578b4` plus the scoped required owner, compiler SHA-256 `5b62561200fde0da9773d76662671157c424afa2aaab3bd3691d05cec19a3d04`.
- Both stages preserve all 26 saved IL-verified assemblies and 28,275 method bodies. Eleven executable programs, two hosted declaration/deployment checks and eleven native configurations pass. The native checks cover every original lookup entry, cached identity, names and arities, all optional family combinations, emitter reuse and deployment. They do not replace the failed guest observations below.
- Fresh Release verification passes 15,971 regression cases with one existing Windows skip. All three original failing probes remain excluded from passing conformance counts; no source expectation or deadline was relaxed.
